# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/william/Desktop/main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 550)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/unipi-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBoxAddReaction = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxAddReaction.setObjectName("groupBoxAddReaction")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxAddReaction)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(340, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEditProducts = QtWidgets.QLineEdit(self.groupBoxAddReaction)
        self.lineEditProducts.setObjectName("lineEditProducts")
        self.gridLayout_4.addWidget(self.lineEditProducts, 1, 2, 1, 1)
        self.labelReactants = QtWidgets.QLabel(self.groupBoxAddReaction)
        self.labelReactants.setObjectName("labelReactants")
        self.gridLayout_4.addWidget(self.labelReactants, 0, 0, 1, 1)
        self.lineEditReactants = QtWidgets.QLineEdit(self.groupBoxAddReaction)
        self.lineEditReactants.setObjectName("lineEditReactants")
        self.gridLayout_4.addWidget(self.lineEditReactants, 1, 0, 1, 1)
        self.labelProducts = QtWidgets.QLabel(self.groupBoxAddReaction)
        self.labelProducts.setObjectName("labelProducts")
        self.gridLayout_4.addWidget(self.labelProducts, 0, 2, 1, 1)
        self.labelInhibitors = QtWidgets.QLabel(self.groupBoxAddReaction)
        self.labelInhibitors.setObjectName("labelInhibitors")
        self.gridLayout_4.addWidget(self.labelInhibitors, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBoxAddReaction)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBoxAddReaction)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 1, 1, 1)
        self.lineEditInhibitors = QtWidgets.QLineEdit(self.groupBoxAddReaction)
        self.lineEditInhibitors.setObjectName("lineEditInhibitors")
        self.gridLayout_4.addWidget(self.lineEditInhibitors, 1, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 0, 1, 2)
        self.pushButtonAdd = QtWidgets.QPushButton(self.groupBoxAddReaction)
        self.pushButtonAdd.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdd.sizePolicy().hasHeightForWidth())
        self.pushButtonAdd.setSizePolicy(sizePolicy)
        self.pushButtonAdd.setMinimumSize(QtCore.QSize(90, 0))
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pushButtonAdd.setIcon(icon)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.gridLayout_2.addWidget(self.pushButtonAdd, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBoxAddReaction, 0, 0, 1, 1)
        self.groupBoxReactionSystem = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxReactionSystem.setEnabled(True)
        self.groupBoxReactionSystem.setObjectName("groupBoxReactionSystem")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxReactionSystem)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonDelete = QtWidgets.QPushButton(self.groupBoxReactionSystem)
        self.pushButtonDelete.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDelete.sizePolicy().hasHeightForWidth())
        self.pushButtonDelete.setSizePolicy(sizePolicy)
        self.pushButtonDelete.setMinimumSize(QtCore.QSize(90, 0))
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pushButtonDelete.setIcon(icon)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.gridLayout_3.addWidget(self.pushButtonDelete, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 2)
        self.listWidgetReactions = QtWidgets.QListWidget(self.groupBoxReactionSystem)
        self.listWidgetReactions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidgetReactions.setAlternatingRowColors(True)
        self.listWidgetReactions.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidgetReactions.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidgetReactions.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidgetReactions.setModelColumn(0)
        self.listWidgetReactions.setObjectName("listWidgetReactions")
        self.gridLayout_3.addWidget(self.listWidgetReactions, 0, 0, 1, 3)
        self.gridLayout_6.addWidget(self.groupBoxReactionSystem, 1, 0, 1, 1)
        self.groupBoxCalculator = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxCalculator.setEnabled(True)
        self.groupBoxCalculator.setObjectName("groupBoxCalculator")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBoxCalculator)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelSymbols = QtWidgets.QLabel(self.groupBoxCalculator)
        self.labelSymbols.setObjectName("labelSymbols")
        self.gridLayout.addWidget(self.labelSymbols, 1, 0, 1, 1)
        self.lineEditCalculatorSteps = QtWidgets.QLineEdit(self.groupBoxCalculator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCalculatorSteps.sizePolicy().hasHeightForWidth())
        self.lineEditCalculatorSteps.setSizePolicy(sizePolicy)
        self.lineEditCalculatorSteps.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditCalculatorSteps.setObjectName("lineEditCalculatorSteps")
        self.gridLayout.addWidget(self.lineEditCalculatorSteps, 2, 1, 1, 1)
        self.labelSteps = QtWidgets.QLabel(self.groupBoxCalculator)
        self.labelSteps.setObjectName("labelSteps")
        self.gridLayout.addWidget(self.labelSteps, 1, 1, 1, 1)
        self.lineEditCalculatorSymbols = QtWidgets.QLineEdit(self.groupBoxCalculator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCalculatorSymbols.sizePolicy().hasHeightForWidth())
        self.lineEditCalculatorSymbols.setSizePolicy(sizePolicy)
        self.lineEditCalculatorSymbols.setObjectName("lineEditCalculatorSymbols")
        self.gridLayout.addWidget(self.lineEditCalculatorSymbols, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.pushButtonCalculate = QtWidgets.QPushButton(self.groupBoxCalculator)
        self.pushButtonCalculate.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCalculate.sizePolicy().hasHeightForWidth())
        self.pushButtonCalculate.setSizePolicy(sizePolicy)
        self.pushButtonCalculate.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.gridLayout_5.addWidget(self.pushButtonCalculate, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBoxCalculator, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBarFile = QtWidgets.QToolBar(MainWindow)
        self.toolBarFile.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBarFile.setObjectName("toolBarFile")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarFile)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setEnabled(True)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.actionSave_as.setIcon(icon)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setEnabled(True)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionNew.setIcon(icon)
        self.actionNew.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionNew.setObjectName("actionNew")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.toolBarFile.addAction(self.actionNew)
        self.toolBarFile.addAction(self.actionOpen)
        self.toolBarFile.addSeparator()
        self.toolBarFile.addAction(self.actionSave)
        self.toolBarFile.addAction(self.actionSave_as)
        self.toolBarFile.addSeparator()
        self.toolBarFile.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.lineEditReactants.returnPressed.connect(self.pushButtonAdd.click)
        self.lineEditProducts.returnPressed.connect(self.pushButtonAdd.click)
        self.lineEditInhibitors.returnPressed.connect(self.pushButtonAdd.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditReactants, self.lineEditProducts)
        MainWindow.setTabOrder(self.lineEditProducts, self.lineEditInhibitors)
        MainWindow.setTabOrder(self.lineEditInhibitors, self.pushButtonAdd)
        MainWindow.setTabOrder(self.pushButtonAdd, self.lineEditCalculatorSymbols)
        MainWindow.setTabOrder(self.lineEditCalculatorSymbols, self.lineEditCalculatorSteps)
        MainWindow.setTabOrder(self.lineEditCalculatorSteps, self.pushButtonCalculate)
        MainWindow.setTabOrder(self.pushButtonCalculate, self.listWidgetReactions)
        MainWindow.setTabOrder(self.listWidgetReactions, self.pushButtonDelete)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RS Calculator"))
        self.groupBoxAddReaction.setTitle(_translate("MainWindow", "Add a reaction"))
        self.lineEditProducts.setStatusTip(_translate("MainWindow", "Example: D E F"))
        self.labelReactants.setText(_translate("MainWindow", "Reactants:"))
        self.lineEditReactants.setStatusTip(_translate("MainWindow", "Example: A B C"))
        self.labelProducts.setText(_translate("MainWindow", "Products:"))
        self.labelInhibitors.setText(_translate("MainWindow", "Inhibitors:"))
        self.label_2.setText(_translate("MainWindow", " | "))
        self.label.setText(_translate("MainWindow", "⟶"))
        self.lineEditInhibitors.setStatusTip(_translate("MainWindow", "Example: F G H (can be empty)"))
        self.pushButtonAdd.setStatusTip(_translate("MainWindow", "Add a reaction (reactants and products required)"))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add"))
        self.groupBoxReactionSystem.setTitle(_translate("MainWindow", "Reaction System"))
        self.pushButtonDelete.setStatusTip(_translate("MainWindow", "Remove selected reactions"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Delete"))
        self.groupBoxCalculator.setTitle(_translate("MainWindow", "Calculator"))
        self.labelSymbols.setText(_translate("MainWindow", "Symbols:"))
        self.lineEditCalculatorSteps.setStatusTip(_translate("MainWindow", "Example: 3"))
        self.labelSteps.setText(_translate("MainWindow", "Steps:"))
        self.lineEditCalculatorSymbols.setStatusTip(_translate("MainWindow", "Example: A B C"))
        self.pushButtonCalculate.setStatusTip(_translate("MainWindow", "Calculate formula based predictor"))
        self.pushButtonCalculate.setText(_translate("MainWindow", "Calculate"))
        self.toolBarFile.setWindowTitle(_translate("MainWindow", "File"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open an existing reaction system"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save changes"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save As..."))
        self.actionSave_as.setToolTip(_translate("MainWindow", "Save As"))
        self.actionSave_as.setStatusTip(_translate("MainWindow", "Save changes under a new name"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setStatusTip(_translate("MainWindow", "Close the application"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionNew.setToolTip(_translate("MainWindow", "New"))
        self.actionNew.setStatusTip(_translate("MainWindow", "Create a new reaction system"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

