# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/william/Desktop/main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WindowCreateRS(object):
    def setupUi(self, WindowCreateRS):
        WindowCreateRS.setObjectName("WindowCreateRS")
        WindowCreateRS.resize(350, 550)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/unipi-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WindowCreateRS.setWindowIcon(icon)
        WindowCreateRS.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(WindowCreateRS)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBoxAddReaction = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxAddReaction.setObjectName("groupBoxAddReaction")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxAddReaction)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(340, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEditProducts = QtWidgets.QLineEdit(self.groupBoxAddReaction)
        self.lineEditProducts.setObjectName("lineEditProducts")
        self.gridLayout_4.addWidget(self.lineEditProducts, 1, 2, 1, 1)
        self.labelReactants = QtWidgets.QLabel(self.groupBoxAddReaction)
        self.labelReactants.setObjectName("labelReactants")
        self.gridLayout_4.addWidget(self.labelReactants, 0, 0, 1, 1)
        self.lineEditReactants = QtWidgets.QLineEdit(self.groupBoxAddReaction)
        self.lineEditReactants.setObjectName("lineEditReactants")
        self.gridLayout_4.addWidget(self.lineEditReactants, 1, 0, 1, 1)
        self.labelProducts = QtWidgets.QLabel(self.groupBoxAddReaction)
        self.labelProducts.setObjectName("labelProducts")
        self.gridLayout_4.addWidget(self.labelProducts, 0, 2, 1, 1)
        self.labelInhibitors = QtWidgets.QLabel(self.groupBoxAddReaction)
        self.labelInhibitors.setObjectName("labelInhibitors")
        self.gridLayout_4.addWidget(self.labelInhibitors, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBoxAddReaction)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBoxAddReaction)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 1, 1, 1)
        self.lineEditInhibitors = QtWidgets.QLineEdit(self.groupBoxAddReaction)
        self.lineEditInhibitors.setObjectName("lineEditInhibitors")
        self.gridLayout_4.addWidget(self.lineEditInhibitors, 1, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 0, 1, 2)
        self.pushButtonAdd = QtWidgets.QPushButton(self.groupBoxAddReaction)
        self.pushButtonAdd.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdd.sizePolicy().hasHeightForWidth())
        self.pushButtonAdd.setSizePolicy(sizePolicy)
        self.pushButtonAdd.setMinimumSize(QtCore.QSize(90, 0))
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pushButtonAdd.setIcon(icon)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.gridLayout_2.addWidget(self.pushButtonAdd, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBoxAddReaction, 0, 0, 1, 1)
        self.groupBoxReactionSystem = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxReactionSystem.setEnabled(True)
        self.groupBoxReactionSystem.setObjectName("groupBoxReactionSystem")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxReactionSystem)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonDelete = QtWidgets.QPushButton(self.groupBoxReactionSystem)
        self.pushButtonDelete.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDelete.sizePolicy().hasHeightForWidth())
        self.pushButtonDelete.setSizePolicy(sizePolicy)
        self.pushButtonDelete.setMinimumSize(QtCore.QSize(90, 0))
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pushButtonDelete.setIcon(icon)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.gridLayout_3.addWidget(self.pushButtonDelete, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 2)
        self.listWidgetReactions = QtWidgets.QListWidget(self.groupBoxReactionSystem)
        self.listWidgetReactions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidgetReactions.setAlternatingRowColors(True)
        self.listWidgetReactions.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidgetReactions.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidgetReactions.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidgetReactions.setModelColumn(0)
        self.listWidgetReactions.setObjectName("listWidgetReactions")
        self.gridLayout_3.addWidget(self.listWidgetReactions, 0, 0, 1, 3)
        self.gridLayout_6.addWidget(self.groupBoxReactionSystem, 1, 0, 1, 1)
        self.groupBoxCalculator = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxCalculator.setEnabled(True)
        self.groupBoxCalculator.setObjectName("groupBoxCalculator")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBoxCalculator)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelSymbols = QtWidgets.QLabel(self.groupBoxCalculator)
        self.labelSymbols.setObjectName("labelSymbols")
        self.gridLayout.addWidget(self.labelSymbols, 1, 0, 1, 1)
        self.lineEditCalculatorSteps = QtWidgets.QLineEdit(self.groupBoxCalculator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCalculatorSteps.sizePolicy().hasHeightForWidth())
        self.lineEditCalculatorSteps.setSizePolicy(sizePolicy)
        self.lineEditCalculatorSteps.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditCalculatorSteps.setObjectName("lineEditCalculatorSteps")
        self.gridLayout.addWidget(self.lineEditCalculatorSteps, 2, 1, 1, 1)
        self.labelSteps = QtWidgets.QLabel(self.groupBoxCalculator)
        self.labelSteps.setObjectName("labelSteps")
        self.gridLayout.addWidget(self.labelSteps, 1, 1, 1, 1)
        self.lineEditCalculatorSymbols = QtWidgets.QLineEdit(self.groupBoxCalculator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCalculatorSymbols.sizePolicy().hasHeightForWidth())
        self.lineEditCalculatorSymbols.setSizePolicy(sizePolicy)
        self.lineEditCalculatorSymbols.setObjectName("lineEditCalculatorSymbols")
        self.gridLayout.addWidget(self.lineEditCalculatorSymbols, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.pushButtonCalculate = QtWidgets.QPushButton(self.groupBoxCalculator)
        self.pushButtonCalculate.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCalculate.sizePolicy().hasHeightForWidth())
        self.pushButtonCalculate.setSizePolicy(sizePolicy)
        self.pushButtonCalculate.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.gridLayout_5.addWidget(self.pushButtonCalculate, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBoxCalculator, 2, 0, 1, 1)
        WindowCreateRS.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(WindowCreateRS)
        self.statusbar.setObjectName("statusbar")
        WindowCreateRS.setStatusBar(self.statusbar)
        self.toolBarFile = QtWidgets.QToolBar(WindowCreateRS)
        self.toolBarFile.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBarFile.setObjectName("toolBarFile")
        WindowCreateRS.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarFile)
        self.menubar = QtWidgets.QMenuBar(WindowCreateRS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        WindowCreateRS.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(WindowCreateRS)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(WindowCreateRS)
        self.actionSave.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(WindowCreateRS)
        self.actionSave_as.setEnabled(True)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.actionSave_as.setIcon(icon)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtWidgets.QAction(WindowCreateRS)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNew = QtWidgets.QAction(WindowCreateRS)
        self.actionNew.setEnabled(True)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionNew.setIcon(icon)
        self.actionNew.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionNew.setObjectName("actionNew")
        self.toolBarFile.addAction(self.actionNew)
        self.toolBarFile.addAction(self.actionOpen)
        self.toolBarFile.addSeparator()
        self.toolBarFile.addAction(self.actionSave)
        self.toolBarFile.addAction(self.actionSave_as)
        self.toolBarFile.addSeparator()
        self.toolBarFile.addAction(self.actionQuit)

        self.retranslateUi(WindowCreateRS)
        self.lineEditReactants.returnPressed.connect(self.pushButtonAdd.click)
        self.lineEditProducts.returnPressed.connect(self.pushButtonAdd.click)
        self.lineEditInhibitors.returnPressed.connect(self.pushButtonAdd.click)
        QtCore.QMetaObject.connectSlotsByName(WindowCreateRS)
        WindowCreateRS.setTabOrder(self.lineEditReactants, self.lineEditProducts)
        WindowCreateRS.setTabOrder(self.lineEditProducts, self.lineEditInhibitors)
        WindowCreateRS.setTabOrder(self.lineEditInhibitors, self.pushButtonAdd)
        WindowCreateRS.setTabOrder(self.pushButtonAdd, self.lineEditCalculatorSymbols)
        WindowCreateRS.setTabOrder(self.lineEditCalculatorSymbols, self.lineEditCalculatorSteps)
        WindowCreateRS.setTabOrder(self.lineEditCalculatorSteps, self.pushButtonCalculate)
        WindowCreateRS.setTabOrder(self.pushButtonCalculate, self.listWidgetReactions)
        WindowCreateRS.setTabOrder(self.listWidgetReactions, self.pushButtonDelete)

    def retranslateUi(self, WindowCreateRS):
        _translate = QtCore.QCoreApplication.translate
        WindowCreateRS.setWindowTitle(_translate("WindowCreateRS", "Reaction System Calculator"))
        self.groupBoxAddReaction.setTitle(_translate("WindowCreateRS", "Add a reaction"))
        self.lineEditProducts.setStatusTip(_translate("WindowCreateRS", "Example: D E F"))
        self.labelReactants.setText(_translate("WindowCreateRS", "Reactants:"))
        self.lineEditReactants.setStatusTip(_translate("WindowCreateRS", "Example: A B C"))
        self.labelProducts.setText(_translate("WindowCreateRS", "Products:"))
        self.labelInhibitors.setText(_translate("WindowCreateRS", "Inhibitors:"))
        self.label_2.setText(_translate("WindowCreateRS", " | "))
        self.label.setText(_translate("WindowCreateRS", "⟶"))
        self.lineEditInhibitors.setStatusTip(_translate("WindowCreateRS", "Example: F G H (can be empty)"))
        self.pushButtonAdd.setStatusTip(_translate("WindowCreateRS", "Add a reaction (reactants and products required)"))
        self.pushButtonAdd.setText(_translate("WindowCreateRS", "Add"))
        self.groupBoxReactionSystem.setTitle(_translate("WindowCreateRS", "Reaction System"))
        self.pushButtonDelete.setStatusTip(_translate("WindowCreateRS", "Remove selected reactions"))
        self.pushButtonDelete.setText(_translate("WindowCreateRS", "Delete"))
        self.groupBoxCalculator.setTitle(_translate("WindowCreateRS", "Calculator"))
        self.labelSymbols.setText(_translate("WindowCreateRS", "Symbols:"))
        self.lineEditCalculatorSteps.setStatusTip(_translate("WindowCreateRS", "Example: 3"))
        self.labelSteps.setText(_translate("WindowCreateRS", "Steps:"))
        self.lineEditCalculatorSymbols.setStatusTip(_translate("WindowCreateRS", "Example: A B C"))
        self.pushButtonCalculate.setStatusTip(_translate("WindowCreateRS", "Calculate formula based predictor"))
        self.pushButtonCalculate.setText(_translate("WindowCreateRS", "Calculate"))
        self.toolBarFile.setWindowTitle(_translate("WindowCreateRS", "File"))
        self.actionOpen.setText(_translate("WindowCreateRS", "Open..."))
        self.actionOpen.setToolTip(_translate("WindowCreateRS", "Open"))
        self.actionOpen.setStatusTip(_translate("WindowCreateRS", "Open an existing reaction system"))
        self.actionOpen.setShortcut(_translate("WindowCreateRS", "Ctrl+O"))
        self.actionSave.setText(_translate("WindowCreateRS", "Save"))
        self.actionSave.setToolTip(_translate("WindowCreateRS", "Save"))
        self.actionSave.setStatusTip(_translate("WindowCreateRS", "Save changes"))
        self.actionSave.setShortcut(_translate("WindowCreateRS", "Ctrl+S"))
        self.actionSave_as.setText(_translate("WindowCreateRS", "Save As..."))
        self.actionSave_as.setToolTip(_translate("WindowCreateRS", "Save As"))
        self.actionSave_as.setStatusTip(_translate("WindowCreateRS", "Save changes under a new name"))
        self.actionSave_as.setShortcut(_translate("WindowCreateRS", "Ctrl+Shift+S"))
        self.actionQuit.setText(_translate("WindowCreateRS", "Quit"))
        self.actionQuit.setStatusTip(_translate("WindowCreateRS", "Close the application"))
        self.actionQuit.setShortcut(_translate("WindowCreateRS", "Ctrl+Q"))
        self.actionNew.setText(_translate("WindowCreateRS", "New..."))
        self.actionNew.setToolTip(_translate("WindowCreateRS", "New"))
        self.actionNew.setStatusTip(_translate("WindowCreateRS", "Create a new reaction system"))
        self.actionNew.setShortcut(_translate("WindowCreateRS", "Ctrl+N"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowCreateRS = QtWidgets.QMainWindow()
    ui = Ui_WindowCreateRS()
    ui.setupUi(WindowCreateRS)
    WindowCreateRS.show()
    sys.exit(app.exec_())

